pamo/pamo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace="web")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pamo/web/urls.py
from django.contrib import admin
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


app_name = 'web'

urlpatterns = [
    path('', views.index, name="index"),
    # path('admin/', admin.site.urls),
    path('cars/', views.cars_page, name='cars'),
    path('cars/<int:car_id>/', views.cars_details, name='cars_details'),
]

pamo/web/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib.auth.models import User
# Create your models here.


class vehicle(models.Model):

    image = models.FileField(null=True)
    name = models.CharField(max_length=100, default="abc")
    brand = models.CharField(max_length=20, choices=(('tata', 'TATA'), ('mahindra',
                                                                        'Mahindra'), ('daewoo', 'Daewoo')))
    vehicle_type = models.CharField(max_length=30, choices=(
        ('scv', "SCV"), ('pickup', "Pick-Up"), ('truck', "Truck"), ('bus', "Bus"), ('car', "Car"), ('tractor', "Agriculture Tractor"), ('others', "Others")), default="others")
    description = models.TextField(max_length=2000, default="")
    added_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.brand

pamo/web/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import vehicle
from django.db.models import Q
from django.http import HttpResponse, request
from django.core import serializers
from django.core.paginator import Paginator
# Create your views here.


def index(request):
    return render(request, 'web/index.html')


def cars_page(request):
    #print('I am here ')
    if request.POST:
        search_term = request.POST['search']
        #search_term = search
        #print('I am here in IF ')
        # print(search_term)
        search_results = vehicle.objects.filter(
            Q(name__icontains=search_term) |
            Q(brand__icontains=search_term) |
            Q(description__icontains=search_term) |
            Q(vehicle_type__icontains=search_term)
        )
        paginator = Paginator(search_results, 9)  # Show 9 vehicles per page.

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        error_message = "Here's your search result for : " + search_term
        context = {
            'error_message': error_message,
            'search_term': search_term,
            'page_obj': page_obj
        }
        return render(request, 'web/cars.html', context)
    elif 'filters' in request.GET:
        filter_ALL=''
        filter_SCV=''
        filter_BUS=''
        filter_TRUCK=''
        filter_CAR=''
        
        filters = request.GET['make']
        if filters == 'all':
            filter_results = vehicle.objects.all()
        else:
            filter_results = vehicle.objects.filter(
                Q(vehicle_type__iexact=filters)
            )
        if('all' in filters):
            filter_ALL='checked'
        elif('SCV' in filters):
            filter_SCV='checked'
        elif('Truck' in filters):
            filter_TRUCK='checked'
        elif('Car' in filters):
            filter_CAR='checked'
        else:
            filter_BUS='checked'
        
        paginator = Paginator(filter_results, 9)  # show 9 vehicles per page
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        error_message = "Here's your filter results: " + filters
        context = {
            'filter_ALL':filter_ALL,
            'filter_SCV':filter_SCV,
            'filter_BUS':filter_BUS,
            'filter_TRUCK':filter_TRUCK,
            'filter_CAR':filter_CAR,
            'error_message': error_message,
            'filters': filters,
            'page_obj': page_obj
        }
        return render(request, 'web/cars.html', context)
    else:
        vehicle_list = vehicle.objects.all()
        paginator = Paginator(vehicle_list, 9)  # Show 9 vehicles per page.

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        #car_list = vehicle.objects.all()
        #print('I am here in else')
        error_message = ''
        context = {
            'error_message': error_message,
            'page_obj': page_obj,
        }
        return render(request, 'web/cars.html', context)


def cars_details(request, car_id):
    print(car_id)
    car_detail = vehicle.objects.get(pk=car_id)
    print(car_detail.name)
    context = {
        'car_detail': car_detail,
    }
    return render(request, 'web/cars_details.html', context)


# def search_cars(request):
#     print('I am here ')
#     if request.GET:
#         search_term = request.GET['search']
#         #search_term = search
#         print('I am here in IF ')
#         print(search_term)
#         search_results = vehicle.objects.filter(
#             Q(name__icontains=search_term) |
#             Q(brand__icontains=search_term) |
#             Q(description__icontains=search_term) |
#             Q(vehicle_type__icontains=search_term)
#         )
#         error_message = "Here's your search result for : " + search_term
#         context = {
#             'error_message': error_message,
#             'search_term': search_term,
#             'page_obj': search_results
#         }
#         return render(request, 'web/cars.html', context)
#     else:
#         car_list = vehicle.objects.all()
#         print('I am here in else')
#         error_message = 'Nothing realted to your search'
#         context = {
#             'error_message': error_message,
#             'page_obj': car_list,
#         }
#         return render(request, 'web/cars.html', context)

pamo/web/templates/web/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{% block title %}{% endblock %}</title>
    <link
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'css/font-awesome.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'magnific-popup/magnific-popup.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    {% block css %} {% endblock %}
  </head>
  <body id="home">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#home">
          <img
            src="{% static 'images/Logo.png' %}"
            alt="Panafrique
            Motors"
            width="130"
            height="50"
        /></a>
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% block menu %} {% endblock %}
        </div>
      </div>
    </nav>
    {% block body %} {% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    {% block scripts %} {% endblock %}
  </body>
</html>

pamo/web/templates/web/base_alt.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>{% block title %}{% endblock %}</title>
    <link
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'css/font-awesome.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'magnific-popup/magnific-popup.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'css/creative.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    {% block css %} {% endblock %}
  </head>
  <body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white" id="altNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'web:index' %}" id="altNav">
          <img
            src="{% static 'images/Logo.png' %}"
            alt="Panafrique
          Motors"
            width="150"
            height="50"
          />
        </a>
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          {% block menu %} {% endblock %}
        </div>
      </div>
    </nav>
    {% block body %} {% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    {% block scripts %} {% endblock %}
  </body>
</html>

pamo/web/templates/web/cars.html
{% extends 'web/base_alt.html' %} {% load static %} {% block title % }Cars{ %
endblock %} {% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/nouislider.css' %}"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/css_style.default.css' %}"
  id="theme-stylesheet"
/>
<script src="{% static 'js/nouislider.min.js' %}"></script>
{% endblock %} {% block menu %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <form class="form-inline my-2 my-lg-0" id="searchbar" method="POST" action="{% url 'web:cars' %}">
      {% csrf_token %}
      <input
        class="form-control mr-sm-2"
        type="search"
        placeholder="Search"
        aria-label="Search"
        name="search"
        placeholder="Search"
        id="search"
      />
      <button
        class="btn btn-outline-success my-2 my-sm-0"
        type="submit"
        id="submit"
      >
        Search
      </button>
    </form>
  </li>
</ul>
{% endblock %} {% block body %}
<section class="hero hero-page gray-bg padding-small">
  <div class="container">
    <div class="row d-flex">
      <div class="col-lg-9 order-2 order-lg-1">
        <h1>Catalogue</h1>
        <p class="lead text-muted">All the available vehicles...</p>
      </div>
      <div class="col-lg-3 text-right order-1 order-lg-2">
        <ul class="breadcrumb justify-content-lg-end">
          <li class="breadcrumb-item">
            <a href="{% url 'web:index' %}">Home</a>
          </li>
          <li class="breadcrumb-item active">Catalogue</li>
        </ul>
      </div>
    </div>
  </div>
</section>
<main>
  <div class="container">
    <div class="row">
      <!-- Sidebar-->
      <div class="sidebar col-xl-3 col-lg-4 sidebar">
        <form id="filter" action="{% url 'web:cars' %}" method="GET">
          <div class="block">
            <h6 class="text-uppercase">Build type</h6>
            <div class="form-group mb-1">
              <input
                id="all"
                type="radio"
                name="make"
                
                class="radio-template"
                value="all"

                {{filter_ALL}}
              />
              <label for="all">All</label>
            </div>
            <div class="form-group mb-1">
                <input id="SCV" type="radio" name="make" class="radio-template" value="SCV" {{filter_SCV}}>
                <label for="SCV">SCV</label>
            </div>
            <div class="form-group mb-1">
                  <input id="Bus" type="radio" name="make" class="radio-template" value="Bus" {{filter_BUS}}>
                  <label for="Bus">Bus</label>
            </div>
            <div class="form-group mb-1">
                  <input id="Truck" type="radio" name="make" class="radio-template" value="Truck" {{filter_TRUCK}}>
                  <label for="Truck">Truck</label>
            </div>
            <div class="form-group mb-1">
                  <input id="Car" type="radio" name="make" class="radio-template" value="Car" {{filter_CAR}}>
                  <label for="Car">Car</label>
            </div>
          </div>
          <button
          class="btn btn-outline-success my-2 my-sm-0"
          type="submit"
          id="filters"
          name="filters"
          >
          Filter
         </button>
        </form>
      </div>
      <!-- /Sidebar end-->
      <!-- Grid -->
      <div class="products-grid col-xl-9 col-lg-8 sidebar-left">
        <div class="row grid">
          <!-- item-->
          {% if page_obj %} {% for vehicles in page_obj %}
          <div class="card my-2 mx-2 blue-card">
            <img class="image"
            src="{% if vehicles.image %}
            {{vehicles.image.url}}
            {% else %}
            {% static 'images/car.jpg' %}
            {% endif %}"
            class="img-fluid"/>
            <div class="card-header">
              <a href="{% url 'web:cars_details' vehicles.pk %}" class="text-bold header-link">{{vehicles.name}} </a>
            </div>
            <div class="card-body pb-0">
              <p>
                {{vehicles.brand}}
              </p>
            </div>
          </div>
          {% endfor %} {% else %}
          <p class="d-block font-weight-light my-2 heading">No vehicle</p>
          {% endif %}
        </div>

        <br />
        <!-- page-navigation -->
        <nav
          aria-label="page navigation example"
          class="d-flex justify-content-center"
        >
        <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
            </span>
        </div>
        </nav>
      </div>
      <!-- / Grid End-->
    </div>
  </div>
</main>
{% endblock %}

pamo/web/templates/web/cars_details.html
{% extends 'web/base_alt.html' %}
{% load static %}
{% block title %}{{ car.brand }} {{ car.name }}{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/css_style.default.css' %}" id="theme-stylesheet">
{% endblock %}

{% block menu %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'web:cars' %}">Cars</a>
        </li>
    </ul>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h3 class="my-4">{{ car.brand }}</h3>
            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-12">

                <div class="card">


            <div
              id="carouselExampleIndicators"
              class="carousel slide"
              data-ride="carousel"
            >
              <ol class="carousel-indicators">
                <li
                  data-target="#carouselExampleIndicators"
                  data-slide-to="0"
                  class="active"
                ></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
              </ol>
              <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div
                  class="carousel-item active"
                  style="background-image: url({{car_detail.image.url}});"
                >
                  <div class="carousel-caption d-none d-md-block">
                    <!-- <h2 class="display-4">First Slide</h2>
                    <p class="lead">This is a description for the first slide.</p> -->
                  </div>
                </div>
                <!-- Slide Two - Set the background image for this slide in the line below -->
                <div
                  class="carousel-item"
                  style="background-image: url({{car_detail.image.url}});"
                >
                  <div class="carousel-caption d-none d-md-block">
                    <!-- <h2 class="display-4">Second Slide</h2>
                    <p class="lead">This is a description for the second slide.</p> -->
                  </div>
                </div>
                <!-- Slide Three - Set the background image for this slide in the line below -->
                <div
                  class="carousel-item img-fluid"
                  style="background-image: {% if car_detail.image %} url({{car_detail.image.url}}); {% else %}
                  url('images/car.jpg');
                  {% endif %}"
                >
                  <div class="carousel-caption d-none d-md-block">
                    <!-- <h2 class="display-4">Third Slide</h2>
                    <p class="lead">This is a description for the third slide.</p> -->
                  </div>
                </div>
              </div>
              <a
                class="carousel-control-prev"
                href="#carouselExampleIndicators"
                role="button"
                data-slide="prev"
              >
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a
                class="carousel-control-next"
                href="#carouselExampleIndicators"
                role="button"
                data-slide="next"
              >
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
                    
                    <div class="card-body">
                        <h3 class="card-title">{{ car_detail.name }}</h3>
                        <p class="card-text">{{ car_detail.description }}</p>
                    </div>
                </div>
                <!-- /.card -->

                <div class="card card-outline-secondary my-4">
                    <div class="card-header">
                        Specification
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <td>
                                    Car type
                                </td>
                                <td>
                                    {{ car_detail.vehicle_type }}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col-lg-9 -->
        </div>
    </div>
    {% endblock %}

pamo/web/templates/web/index.html
{% extends 'web/base.html' %} {% load static %} {% block title %} Panafrique
Motors{% endblock %} {% block css %}
<link
  href="{% static 'css/creative.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
{% endblock %} {% block menu %}
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#AboutUs">About Us</a>
  </li>
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#services">Services</a>
  </li>
  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#cars">Catalogue</a>
  </li>

  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#Location">Locations</a>
  </li>

  <li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
  </li>
</ul>
{% endblock %} {% block body %}

<header>
  <div
    id="carouselExampleIndicators"
    class="carousel slide"
    data-ride="carousel"
  >
    <ol class="carousel-indicators">
      <li
        data-target="#carouselExampleIndicators"
        data-slide-to="0"
        class="active"
      ></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <!-- Slide One - Set the background image for this slide in the line below -->
      <div
        class="carousel-item active"
        style="background-image: url('static/images/caro1.jpg');"
      >
        <div class="carousel-caption d-none d-md-block">
          <!-- <h2 class="display-4">First Slide</h2>
          <p class="lead">This is a description for the first slide.</p> -->
        </div>
      </div>
      <!-- Slide Two - Set the background image for this slide in the line below -->
      <div
        class="carousel-item"
        style="background-image: url('static/images/caro2.jpg');"
      >
        <div class="carousel-caption d-none d-md-block">
          <!-- <h2 class="display-4">Second Slide</h2>
          <p class="lead">This is a description for the second slide.</p> -->
        </div>
      </div>
      <!-- Slide Three - Set the background image for this slide in the line below -->
      <div
        class="carousel-item"
        style="background-image: url('static/images/caro3.jpg');"
      >
        <div class="carousel-caption d-none d-md-block">
          <!-- <h2 class="display-4">Third Slide</h2>
          <p class="lead">This is a description for the third slide.</p> -->
        </div>
      </div>
    </div>
    <a
      class="carousel-control-prev"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a
      class="carousel-control-next"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</header>

<!-- ABOUT US -->
<section class="bg-dark text-white" id="AboutUs">
  <div class="container text-center">
    <h2 class="mb-4">Check out all the cars!</h2>
    <a class="btn btn-dark btn-xl sr-button" href="{% url 'web:cars' %}"
      >Click here</a
    >
  </div>
</section>

<!-- Services -->
<section class="bg-white text-bold" id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Services</h2>
        <hr class="my-4" /> 
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-cog fa-spin text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Garage</h3>
          <p class="text-muted mb-0">
            We provide routine check ups and service for your vehicle.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-clock-o text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">On time delivery</h3>
          <p class="text-muted mb-0">
            We deliver it on the scheduled date.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-newspaper-o text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Always updated</h3>
          <p class="text-muted mb-0">
            We update our stocks and catalogue with the latest and greatest.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-life-ring text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Support</h3>
          <p class="text-muted mb-0">
            We provide support for your vehicle, even after it is delivered to
            you!
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="bg-light" id="cars">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Catalogue</h2>
        <hr class="my-4" />
      </div>
      <div class="col-lg-12 mx-auto text-center">
        <div
          id="carousel_catalogue"
          class="carousel slide"
          data-ride="carousel"
        >
          <ol class="carousel-indicators">
            <li
              data-target="#carousel_catalogue"
              data-slide-to="0"
              class="active"
            ></li>
            <li data-target="#carousel_catalogue" data-slide-to="1"></li>
            <li data-target="#carousel_catalogue" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div
              class="carousel-item active"
              style="background-image: url('static/images/caro1.jpg');"
            >
              <div class="carousel-caption d-none d-md-block">
                <!-- <h2 class="display-4">First Slide</h2>
          <p class="lead">This is a description for the first slide.</p> -->
              </div>
            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div
              class="carousel-item"
              style="background-image: url('static/images/caro2.jpg');"
            >
              <div class="carousel-caption d-none d-md-block">
                <!-- <h2 class="display-4">Second Slide</h2>
          <p class="lead">This is a description for the second slide.</p> -->
              </div>
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div
              class="carousel-item"
              style="background-image: url('static/images/caro3.jpg');"
            >
              <div class="carousel-caption d-none d-md-block">
                <!-- <h2 class="display-4">Third Slide</h2>
          <p class="lead">This is a description for the third slide.</p> -->
              </div>
            </div>
          </div>
          <a
            class="carousel-control-prev"
            href="#carousel_catalogue"
            role="button"
            data-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a
            class="carousel-control-next"
            href="#carousel_catalogue"
            role="button"
            data-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Location -->
<section class="masthead text-center text-black-bold d-flex bg-transparent" id="Location">
  <div class="container my-auto">
      <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">Location</h2>
          <hr class="my-4" />
        </div>
      </div>
    </div>
    <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
          <i class="fa fa-4x fa-location-arrow text-primary mb-3 sr-icons"></i>
          <h3 class="mb-3">Lubumbashi</h3>
          <p class="text-muted mb-0">
            2143, Blvd Lubumba, C/ Kampemba, Province du Hout Katanga, DRC.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box mt-5 mx-auto">
              <i class="fa fa-4x fa-location-arrow text-primary mb-3 sr-icons"></i>
              <h3 class="mb-3">Kolwezi</h3>
              <p class="text-muted mb-0">
                5170,Route Likasi,C/Manika,Kolwezi, Province De Lualaba, DRC.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- contact -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 class="section-heading">Let's Get In Touch!</h2>
        <hr class="my-4" />
        <p class="mb-5">
          Ready to buy the next car from us? That's great! Give us a call or
          send us an email and we will get back to you as soon as possible!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 ml-auto text-center">
        <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
        <p>Sales: +243 906 605 555</p>
        <p>Service: +243 905 605 555</p>
        <p>Spares: +243 858 006 494</p>
      </div>
      <div class="col-lg-4 mr-auto text-center">
        <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
        <p>
          Kolwezi:
          <a href="mailto:sales@pan-mo.com">sales@pan-mo.com</a>
        </p>
        <p>
          Lubumbashi:
          <a href="mailto:sales.lshi@pan-mo.com">sales.lshi@pan-mo.com</a>
        </p>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; PAMO 2020</p>
  </div>
  <!-- /.container -->
</footer>

{% endblock %} {% block scripts %}
<script src="{% static 'js/creative.js' %}"></script>
{% endblock %}